name: continous deivery github actions
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select the environment where you want to run
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
          

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: code write
        run: echo "code here"
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: builds code
        run: echo "code build"
  test:
    needs: [code,build]
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: echo "runs tests"
  deploy:
    if: inputs.environment == 'dev'
    needs: [code,build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploys
        run: echo "deploying"
