name: Demo Hello Github actions file
on: workflow_dispatch
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to users
        run: echo "Hello everyone"
      - name: Say hello to username
        run: echo "Hello $USER"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: shows docker and python version
        run: docker --version && python --version
    
    
    
