name: Demo Hello Github actions file
on:
  push:
    branches: [main]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to users
        run: echo "Hello everyone"
      - name: Say hello to username
        run: echo "Hello $USER"
    
